// Host-only procedural eye masks: compile, then redirect stdout to eye_masks.h.
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <vector>
constexpr int W=144,H=176,N=8;
float segment(float x,float y,float ax,float ay,float bx,float by) {
  float dx=bx-ax,dy=by-ay,t=std::clamp(((x-ax)*dx+(y-ay)*dy)/(dx*dx+dy*dy),0.f,1.f);
  return std::hypot(x-ax-t*dx,y-ay-t*dy);
}
bool shape(int mood,float x,float y) {
  if(mood==0) {
    for(int k=0;k<40;k++) {
      float a=k/40.f,b=(k+1)/40.f;
      if(segment(x,y,-44+88*a,12-136*a*(1-a),-44+88*b,12-136*b*(1-b))<11) return true;
    }
    return false;
  }
  if(mood==5) { float a=x/45,b=-(y+1)/48,q=a*a+b*b-1; return q*q*q-a*a*b*b*b<=0; }
  if(mood==6) return x*x/(48*48)+y*y/(68*68)<=1;
  float halfW=49,halfH=mood==2?10:62,r=mood==2?10:31;
  float dx=std::max(std::abs(x)-(halfW-r),0.f),dy=std::max(std::abs(y)-(halfH-r),0.f);
  if(dx*dx+dy*dy>r*r) return false;
  if(mood==3&&y< -38-0.40f*x) return false;
  if(mood==4&&y< -38+0.40f*x) return false;
  if(mood==7&&y< -4) return false;
  return true;
}
int main() {
  puts("#pragma once\n#include <stdint.h>\n// Generated by tools/generate_eyes.cpp.\nnamespace eye_masks {\nconstexpr int W=144,H=176;\nstatic const uint8_t pixels[8][W*H]={");
  for(int mood=0;mood<N;mood++) {
    std::vector<float> mask(W*H),horizontal(W*H),blur(W*H);
    for(int y=0;y<H;y++) for(int x=0;x<W;x++) {
      int hits=0;
      for(int sy=0;sy<4;sy++) for(int sx=0;sx<4;sx++) hits+=shape(mood,x+(sx+.5f)/4-W/2,y+(sy+.5f)/4-H/2);
      mask[y*W+x]=hits/16.f;
    }
    float weights[19],total=0;
    for(int i=-9;i<=9;i++) { weights[i+9]=std::exp(-i*i/18.f); total+=weights[i+9]; }
    for(float &w:weights) w/=total;
    for(int y=0;y<H;y++) for(int x=0;x<W;x++) for(int k=-9;k<=9;k++) if(x+k>=0&&x+k<W) horizontal[y*W+x]+=mask[y*W+x+k]*weights[k+9];
    for(int y=0;y<H;y++) for(int x=0;x<W;x++) for(int k=-9;k<=9;k++) if(y+k>=0&&y+k<H) blur[y*W+x]+=horizontal[(y+k)*W+x]*weights[k+9];
    puts("{");
    for(int i=0;i<W*H;i++) printf("%d,%s",int(std::lround(255*(mask[i]+(1-mask[i])*blur[i]*.32f))),(i+1)%W==0?"\n":"");
    puts("},");
  }
  puts("};\n}");
}
