"""Offline 1-bit CJK font and single-syllable candidate index for the MCU.
Requires Pillow and pypinyin==0.55.0. Font: bundled OFL Noto Sans SC.
Pinyin data: python-pinyin (MIT); no Python dependency on the device.
"""
from pathlib import Path
from collections import defaultdict
import re
from PIL import Image, ImageDraw, ImageFont
from pypinyin import pinyin, Style

root=Path(__file__).resolve().parents[1]
hanzi=[]
for high in range(0xB0,0xF8):
    for low in range(0xA1,0xFF):
        try: ch=bytes((high,low)).decode('gb2312')
        except UnicodeDecodeError: continue
        if '\u4e00'<=ch<='\u9fff': hanzi.append(ch)
hanzi_set=set(hanzi)
chars=sorted(hanzi_set|set('！？，。；：、（）《》“”…'),key=ord)
font=ImageFont.truetype(str(root/'assets/NotoSansSC.ttf'),24)
font.set_variation_by_axes([550])
pixels=[]
for ch in chars:
    img=Image.new('L',(24,24))
    ImageDraw.Draw(img).text((0,0),ch,font=font,fill=255,anchor='lt')
    data=list(img.getdata())
    for start in range(0,576,8):
        value=0
        for bit in range(8): value|=(data[start+bit]>=100)<<(7-bit)
        pixels.append(value)
priority='营业中下班了在厕所不干放轻松饭的是一我你他她它们这那有和就也都要好人来去是时间上天大小多少可以没很到说想心开快工作休息加油爱生活快乐朋友今天明见谢谢您好早晚安吃喝水学习等待请勿打扰正在会议忙碌欢迎光临'
order=list(dict.fromkeys(priority+''.join(hanzi)))
groups=defaultdict(list)
for ch in order:
    if ch not in hanzi_set: continue
    for syllable in pinyin(ch,style=Style.NORMAL,heteronym=True,v_to_u=False)[0]:
        if re.fullmatch('[a-z]{1,6}',syllable) and ch not in groups[syllable]: groups[syllable].append(ch)
out=['#pragma once','#include <stdint.h>','// Generated by tools/generate_lightboard_font.py. Noto OFL; pypinyin MIT.','namespace lightfont {',
     f'constexpr int COUNT={len(chars)},SIDE=24;',
     'static const uint16_t codes[]={'+','.join(str(ord(c)) for c in chars)+'};',
     'static const uint8_t pixels[]={']
out.extend(','.join(str(p) for p in pixels[i:i+72])+',' for i in range(0,len(pixels),72))
out+=['};','struct Pinyin { const char *key,*characters; };','static const Pinyin dictionary[]={']
out.extend('{"'+key+'","'+''.join(groups[key])+'"},' for key in sorted(groups))
out+=['};','constexpr int PINYIN_COUNT=sizeof(dictionary)/sizeof(dictionary[0]);','}']
(root/'firmware/salary_counter/lightboard_font.h').write_text('\n'.join(out)+'\n')
print(f'Generated {len(chars)} CJK glyphs ({len(pixels)} bitmap bytes), {len(groups)} pinyin syllables')
